info:
  component: Config Server
spring:
  application:
    name: configserver
  profiles:
    active: native

server:
  port: 8888
management:
  context_path: /admin
  
security:
  user: 
    name: admin
    password: foo@bar